### ISSUE TITLE
Create a "Theme" option, bound to separate word lists

### ISSUE THREAD

**Issue by adilio** [thomasrayner/vscode-namegen#5]
The idea is simple.

Add support for a "-Realm" or "-Universe" option, which would trigger the use of a separate word list. This would require the production of separate word lists, one per Universe. Examples are:

- Tolkien/Midde-Earth
- Star Wars
- Star Trek
- Westeros

Self-explanatory. Selecting this option would generate word combinations from that Universe only.

Will supply word lists, as tribute.

Please and thank you.

**Comment by adilio** [comment]
Now I think about it, you could even just use a `-List` param, with some lists supplied, or even allow the user to specify their own list?

**Comment by thomasrayner** [comment]
This is implemented now in 0.1.0, but only adds a `StarWars` option. Everything is in place for more wordlists to be added in the future.
