### ISSUE TITLE
Add LOTR Wordlist

### ISSUE THREAD

**Issue by kilasuit** [thomasrayner/vscode-namegen#7]
Just becuase ......

**Comment by adilio** [comment]
Hi Ryan, I've created a MiddleEarth.txt wordlist, as well as updated StarWars.txt, and submitted as PR:
https://github.com/thomasrayner/vscode-namegen/pull/8

**Comment by thomasrayner** [comment]
Great idea, @kilasuit , and thank you @adilio for adding that wordlist. This will end up in the 0.1.1 version which I'll be pushing in the next 24 hours or so. :)
